# This is a GoReleaser configuration file for dotenvify
# Documentation: https://goreleaser.com

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    main: .

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
  groups:
    - title: '🚀 Features'
      regexp: '^feat'
      order: 0
    - title: '🐛 Bug Fixes'
      regexp: '^fix'
      order: 1
    - title: '⚡ Performance Improvements'
      regexp: '^perf'
      order: 2
    - title: '♻️ Refactoring'
      regexp: '^refactor'
      order: 3
    - title: '📚 Documentation'
      regexp: '^docs'
      order: 4
    - title: '✅ Tests'
      regexp: '^test'
      order: 5
    - title: '🏗️ Build System'
      regexp: '^build'
      order: 6
    - title: '👷 CI'
      regexp: '^ci'
      order: 7
    - title: '🧹 Chore'
      regexp: '^chore'
      order: 8
    - title: '💄 Style'
      regexp: '^style'
      order: 9
  filters:
    exclude:
      - '^chore:'
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: webb1es
    name: dotenvify
  header: |
    # DotEnvify {{.Version}} Release

    ## Summary
    This release of DotEnvify brings new features and improvements to help you manage environment variables more efficiently.

    <!-- You can edit this section manually before each release to provide a human-readable summary -->
  footer: |
    ## Installation

    ### ⭐ Recommended: Package Managers ⭐
    We strongly recommend using package managers for installation as they provide:
    - Automatic updates when new versions are released
    - Easier installation without manual downloading and extracting
    - Proper system integration and path configuration
    - Simplified uninstallation process

    #### Homebrew (macOS and Linux)
    ```bash
    brew install webb1es/tap/dotenvify
    ```

    #### Scoop (Windows)
    ```bash
    scoop bucket add webb1es https://github.com/webb1es/scoop-bucket
    scoop install dotenvify
    ```

    ### Alternative: Manual Installation
    If package managers are not an option for your environment, you can download the appropriate binary for your platform from the assets below. Note that you'll need to manually extract the archive and place the binary in your PATH.

    ## Thank You
    Thanks to all contributors who made this release possible!

brews:
  - name: dotenvify
    repository:
      owner: webb1es
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/webb1es/dotenvify"
    description: "Convert key-value pairs to environment variables"
    license: "MIT"
    install: |
      bin.install "dotenvify"
    test: |
      system "#{bin}/dotenvify", "-h"

scoops:
  - name: dotenvify
    repository:
      owner: webb1es
      name: scoop-bucket
      token: "{{ .Env.SCOOP_BUCKET_TOKEN }}"
    homepage: "https://github.com/webb1es/dotenvify"
    description: "Convert key-value pairs to environment variables"
    license: "MIT"

# NPM package publishing - use filter to run only for one artifact
publishers:
  - name: npm
    cmd: node scripts/publish-npm.js
    env:
      - NPM_TOKEN={{ .Env.NPM_TOKEN }}
      - RELEASE_VERSION={{ .Version }}
      - RELEASE_TAG={{ .Tag }}
    filter:
      filename: "*linux_amd64*"
