before:
  hooks:
    - go mod tidy

builds:
  - id: dotenvify
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    main: .
    binary: dotenvify

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
  groups:
    - title: '🚀 Features'
      regexp: '^feat'
      order: 0
    - title: '🐛 Bug Fixes'
      regexp: '^fix'
      order: 1
    - title: '♻️ Refactoring'
      regexp: '^refactor'
      order: 2
    - title: '📚 Documentation'
      regexp: '^docs'
      order: 3
    - title: '🏗️ Build System'
      regexp: '^build'
      order: 4
  filters:
    exclude:
      - '^chore:'
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: webb1es
    name: dotenvify
  header: |
    # DotEnvify {{.Version}} Release

    This release brings new features and improvements for managing environment variables.
  footer: |
    ## Installation

    ```bash
    npm install -g @webbies.dev/dotenvify
    ```